export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_REPOSITORY_REQUEST = 'GET_REPOSITORY_REQUEST';
export const GET_REPOSITORY_SUCCESS = 'GET_REPOSITORY_SUCCESS';
export const GET_REPOSITORY_FAILURE = 'GET_REPOSITORY_FAILURE';

export const SET_SELECTED_REPOSITORY_REQUEST = 'SET_SELECTED_REPOSITORY_REQUEST';
export const SET_SELECTED_REPOSITORY_SUCCESS = 'SET_SELECTED_REPOSITORY_SUCCESS';
export const SET_SELECTED_REPOSITORY_FAILURE = 'SET_SELECTED_REPOSITORY_FAILURE';